export const meetingAgendas = ["Welcome Note by the Presiding Officer", "Changes / Additions of IC Members and Brief Introductions", "Status of Complaints Received", "Any Other Status", "Upcoming Meeting Dates and Other Activities"];
const escape = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);
export function meetingPrintHtml(row) {
  const date = escape(row.meeting_date?.slice(0, 10).split("-").reverse().join("/"));
  return `<!doctype html><html><head><meta charset="utf-8"><title>Minutes of Meeting</title><style>
  *{box-sizing:border-box}body{margin:0;color:#111;background:white;font:12pt Georgia,'Times New Roman',serif;line-height:1.5}main{max-width:190mm;margin:24px auto;padding:12mm}header{text-align:center;border-bottom:2px solid #333;padding-bottom:12px}h1{font-size:20pt;margin:0}h2{text-align:center;font-size:14pt;margin:20px 0}h3{font-size:12pt;border-bottom:1px solid #999;margin-top:24px}h4{font-size:11pt;margin:16px 0 4px}p{margin:4px 0;white-space:pre-wrap;overflow-wrap:anywhere}table{border-collapse:collapse;width:100%;table-layout:fixed}th,td{border:1px solid #aaa;padding:6px;text-align:left;overflow-wrap:anywhere}th{background:#f3f3f3}.signature{margin:80px 0 0 auto;width:65mm;text-align:center;border-top:1px solid #333;break-inside:avoid}.toolbar{text-align:center;margin:20px}button{padding:8px 18px;margin:0 4px;cursor:pointer}section{break-inside:auto}li{overflow-wrap:anywhere}@page{size:A4;margin:15mm}@media print{.toolbar{display:none}main{max-width:none;margin:0;padding:0}h3,h4{break-after:avoid}thead{display:table-header-group}}
  </style></head><body><div class="toolbar"><button onclick="window.print()">Print</button><button onclick="window.close()">Close</button></div><main>
  <header><h1>${escape(row.company_name)}</h1><p>Internal Committee</p></header><h2>INTERNAL COMMITTEE MEETING - MINUTES OF MEETING</h2>
  <table><tbody><tr><th>Branch</th><td>${escape(row.branch_name)}</td><th>Quarterly Meeting</th><td>Q${escape(row.quarter)} - ${escape(row.year)}</td></tr><tr><th>Date</th><td>${date}</td><th>Time</th><td>${escape(row.meeting_time?.slice(0, 5))}</td></tr><tr><th>Venue / Mode</th><td colspan="3">${escape(row.venue)}</td></tr><tr><th>Presiding Officer</th><td colspan="3">${escape(row.presiding_officer)}</td></tr></tbody></table>
  <h3>Members Present</h3><ol>${String(row.attendees || "").split(/[,\n]+/).filter((name) => name.trim()).map((name) => `<li>${escape(name.trim())}</li>`).join("")}</ol><h3>Agenda &amp; Discussion</h3>
  ${meetingAgendas.map((title, index) => `<section><h4>Agenda ${index + 1} - ${escape(title)}</h4><p>${escape(row[`agenda${index + 1}`] || "-")}</p></section>`).join("")}
  <div class="signature"><p>Signature of Presiding Officer</p><p>Name: ${escape(row.presiding_officer)}</p><p>Date: ${date}</p></div></main></body></html>`;
}
