"""add_phase3_hr_notification_tables

Revision ID: 050d91b6c437
Revises: 4f606a040db9
Create Date: 2026-07-03 07:25:20.920485

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "050d91b6c437"
down_revision: Union[str, None] = "4f606a040db9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_upload_batch",
        sa.Column("batch_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("uploaded_by", sa.BigInteger(), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("total_rows", sa.Integer(), nullable=True),
        sa.Column("success_rows", sa.Integer(), nullable=True),
        sa.Column("failed_rows", sa.Integer(), nullable=True),
        sa.Column("error_report_path", sa.String(length=255), nullable=True),
        sa.Column("status", sa.Enum("Processing", "Completed", "Failed"), nullable=True),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company_master.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["user_master.user_id"],
        ),
        sa.PrimaryKeyConstraint("batch_id"),
    )
    op.create_table(
        "notification",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company_master.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_master.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification")
    op.drop_table("employee_upload_batch")
    # ### end Alembic commands ###
