"""add_phase2_video_training_tables

Revision ID: 4f606a040db9
Revises: 11443287d861
Create Date: 2026-07-02 21:02:38.567310

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f606a040db9"
down_revision: Union[str, None] = "11443287d861"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "language_master",
        sa.Column("language_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("language_name", sa.String(length=50), nullable=True),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("language_id"),
    )
    op.create_table(
        "video_category",
        sa.Column("category_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("category_name", sa.String(length=100), nullable=True),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("category_id"),
    )
    op.create_table(
        "video_master",
        sa.Column("video_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("video_url", sa.String(length=500), nullable=True),
        sa.Column("storage_type", sa.Enum("AWS S3", "Azure Blob", "Local", "MinIO"), nullable=True),
        sa.Column("status", sa.Enum("Draft", "Published", "Archived"), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["video_category.category_id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company_master.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user_master.user_id"],
        ),
        sa.PrimaryKeyConstraint("video_id"),
    )
    op.create_table(
        "assessment_question",
        sa.Column("question_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=True),
        sa.Column("question_text", sa.String(length=500), nullable=True),
        sa.Column("question_type", sa.Enum("MCQ", "True/False", "Scenario"), nullable=True),
        sa.Column("correct_option", sa.String(length=1), nullable=True),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video_master.video_id"],
        ),
        sa.PrimaryKeyConstraint("question_id"),
    )
    op.create_table(
        "assessment_result",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("video_id", sa.Integer(), nullable=True),
        sa.Column("total_questions", sa.Integer(), nullable=True),
        sa.Column("correct_answers", sa.Integer(), nullable=True),
        sa.Column("score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("passing_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("result", sa.Enum("Pass", "Fail"), nullable=True),
        sa.Column("attempt_number", sa.Integer(), nullable=True),
        sa.Column("attempted_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_master.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video_master.video_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "course_assignment",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=True),
        sa.Column("assigned_by", sa.BigInteger(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("assigned_to_user_id", sa.BigInteger(), nullable=True),
        sa.Column("assigned_to_department", sa.String(length=100), nullable=True),
        sa.Column(
            "assign_type", sa.Enum("Individual", "Department", "Company-Wide"), nullable=True
        ),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("passing_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["user_master.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_user_id"],
            ["user_master.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company_master.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video_master.video_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "training_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("video_id", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("watched_seconds", sa.Integer(), nullable=True),
        sa.Column("total_seconds", sa.Integer(), nullable=True),
        sa.Column("completion_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("furthest_position", sa.Integer(), nullable=True),
        sa.Column("last_watched_position", sa.Integer(), nullable=True),
        sa.Column("status", sa.Enum("Not Started", "In Progress", "Completed"), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company_master.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_master.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video_master.video_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "video_language",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=True),
        sa.Column("language_id", sa.Integer(), nullable=True),
        sa.Column("subtitle_path", sa.String(length=255), nullable=True),
        sa.Column("audio_url", sa.String(length=500), nullable=True),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["language_master.language_id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video_master.video_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assessment_option",
        sa.Column("option_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.Column("option_label", sa.String(length=1), nullable=True),
        sa.Column("option_text", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["assessment_question.question_id"],
        ),
        sa.PrimaryKeyConstraint("option_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assessment_option")
    op.drop_table("video_language")
    op.drop_table("training_history")
    op.drop_table("course_assignment")
    op.drop_table("assessment_result")
    op.drop_table("assessment_question")
    op.drop_table("video_master")
    op.drop_table("video_category")
    op.drop_table("language_master")
    # ### end Alembic commands ###
