"""add_phase4_certificate_analytics_tables

Revision ID: 71a229ca0ac3
Revises: 050d91b6c437
Create Date: 2026-07-03 07:34:46.200137

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71a229ca0ac3"
down_revision: Union[str, None] = "050d91b6c437"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_summary",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("report_date", sa.Date(), nullable=True),
        sa.Column("total_employees", sa.Integer(), nullable=True),
        sa.Column("completed", sa.Integer(), nullable=True),
        sa.Column("in_progress", sa.Integer(), nullable=True),
        sa.Column("not_started", sa.Integer(), nullable=True),
        sa.Column("compliance_rate", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company_master.company_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "certificate_template",
        sa.Column("template_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("template_name", sa.String(length=100), nullable=True),
        sa.Column("logo_path", sa.String(length=255), nullable=True),
        sa.Column("font_name", sa.String(length=50), nullable=True),
        sa.Column("signature_path", sa.String(length=255), nullable=True),
        sa.Column("color_code", sa.String(length=20), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Enum("Active", "Inactive"), nullable=True),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company_master.company_id"],
        ),
        sa.PrimaryKeyConstraint("template_id"),
    )
    op.create_table(
        "certificates",
        sa.Column("certificate_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("certificate_number", sa.String(length=100), nullable=True),
        sa.Column("course_name", sa.String(length=200), nullable=True),
        sa.Column("completion_date", sa.Date(), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("qr_code_path", sa.String(length=255), nullable=True),
        sa.Column("pdf_path", sa.String(length=255), nullable=True),
        sa.Column("status", sa.Enum("Valid", "Revoked"), nullable=True),
        sa.Column("created_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company_master.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["certificate_template.template_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_master.user_id"],
        ),
        sa.PrimaryKeyConstraint("certificate_id"),
        sa.UniqueConstraint("certificate_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("certificates")
    op.drop_table("certificate_template")
    op.drop_table("analytics_summary")
    # ### end Alembic commands ###
