"""initial_tables_company_role_user

Revision ID: d04a5453da29
Revises:
Create Date: 2026-07-01 15:28:44.396546

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d04a5453da29"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_master",
        sa.Column("company_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("company_code", sa.String(length=20), nullable=True),
        sa.Column("company_name", sa.String(length=200), nullable=True),
        sa.Column("industry_type", sa.String(length=100), nullable=True),
        sa.Column("website", sa.String(length=200), nullable=True),
        sa.Column("registration_number", sa.String(length=50), nullable=True),
        sa.Column("gst_number", sa.String(length=50), nullable=True),
        sa.Column("employee_strength", sa.Integer(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("contact_person", sa.String(length=100), nullable=True),
        sa.Column("contact_email", sa.String(length=100), nullable=True),
        sa.Column("contact_mobile", sa.String(length=20), nullable=True),
        sa.Column("status", sa.Enum("Active", "Inactive"), nullable=True),
        sa.Column("is_deleted", sa.String(length=1), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("company_id"),
        sa.UniqueConstraint("company_code"),
    )
    op.create_table(
        "role_master",
        sa.Column("role_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role_name", sa.String(length=50), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("role_id"),
    )
    op.create_table(
        "user_master",
        sa.Column("user_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.String(length=30), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("mobile", sa.String(length=20), nullable=True),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("designation", sa.String(length=100), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("manager_id", sa.BigInteger(), nullable=True),
        sa.Column("login_type", sa.Enum("Email", "SSO", "Entra ID"), nullable=True),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("language_preference", sa.Integer(), nullable=True),
        sa.Column("status", sa.Enum("Active", "Inactive"), nullable=True),
        sa.Column("is_deleted", sa.String(length=1), nullable=True),
        sa.Column("joining_date", sa.Date(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company_master.company_id"],
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["user_master.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role_master.role_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("employee_id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_master")
    op.drop_table("role_master")
    op.drop_table("company_master")
    # ### end Alembic commands ###
