SUPER_ADMIN = 1
ADMIN = 2
CLIENT_MANAGEMENT = 3
HR_IC = 4
EMPLOYEE = 5

ROLE_NAMES = {
    SUPER_ADMIN: "Super Admin",
    ADMIN: "Admin",
    CLIENT_MANAGEMENT: "Client / Management",
    HR_IC: "HR / IC",
    EMPLOYEE: "Employee",
}

ROLE_CREATION_RULES = {
    SUPER_ADMIN: {ADMIN},
    ADMIN: {CLIENT_MANAGEMENT},
    CLIENT_MANAGEMENT: {HR_IC},
    HR_IC: {EMPLOYEE},
}

ADMIN_PORTAL_ROLES = {SUPER_ADMIN, ADMIN}
HR_PORTAL_ROLES = {SUPER_ADMIN, ADMIN, CLIENT_MANAGEMENT, HR_IC}
COMPANY_SCOPED_ROLES = {ADMIN, CLIENT_MANAGEMENT, HR_IC}
